### ISSUE TITLE
not able to create image....

### ISSUE THREAD

**Issue by sivakumarsakkarai** [tongueroo/demo-java#2]
Getting below error:

COPY failed: stat /var/lib/docker/tmp/docker-builder069780460/pkg/demo.war: no such file or directory

Please help Me..

**Comment by praful-dhabekar** [comment]
Hey I'm facing the same issue. Did you resolve it by any chance?

Edit: I fixed it!
you have to change pkg/demo.war to target/demo.war in Dockerfile and remove target from .dockerignore
